services:
  - type: web
    name: simple-numbers-bot
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase: false
        value: "7656744783:AAGvO38tzVHkGDu8UAt8uj6Oq-sIbf0xYok"
      - key: WEBHOOK_URL
        fromDatabase: false
        value: "https://<ВАШ_ПУБЛИЧНЫЙ_URL>.onrender.com"
    autoDeploy: true